"""Seal observed validation for exactly the reviewed installed artifact."""
import argparse,hashlib,json,shutil,subprocess
from pathlib import Path
HERE=Path(__file__).resolve().parent
p=argparse.ArgumentParser();p.add_argument('root',type=Path);p.add_argument('install',type=Path);a=p.parse_args();root=a.root;install=a.install.resolve();validation=root/'validation';reviewed=json.loads((validation/'binary-isa-reviewed.json').read_text(encoding='utf-8'));runtime=json.loads((validation/'validation.json').read_text(encoding='utf-8'));comparison=json.loads((validation/'benchmark/comparison.json').read_text(encoding='utf-8'));review=json.loads((HERE/'isa-review.json').read_text(encoding='utf-8'))
assert reviewed['status']=='approved_for_tested_pipeline'
assert reviewed['reviewSha256']==hashlib.sha256((HERE/'isa-review.json').read_bytes()).hexdigest()
assert runtime['status']=='ok' and Path(runtime['executable']).resolve()==install/'blender.exe'
quality=json.loads((validation/'preflight/comparison_metrics.json').read_text(encoding='utf-8'))
assert all(quality[k] for k in ('allFourViewsFit','cameraDriftRejected','lightDriftRejected','modifierGeometryChecked','requestedDimensionsChecked','finalPassVisibilityRestored'))
assert abs(quality['measuredTileRatio']-2)<0.001
assert json.loads((validation/'preflight/preflight_report.json').read_text(encoding='utf-8'))['status']=='pass'
assert runtime['bpy'] and runtime['cycles']['device']=='CPU' and not runtime['cycles']['embreeCompiled']
for file in reviewed['files']:assert hashlib.sha256(Path(file['path']).read_bytes()).hexdigest()==file['sha256'],file['path']
run=next(r for r in reversed(comparison['runs']) if r['backend']=='baseline');real=Path(run['output']);worker=json.loads((real/'worker.report.json').read_text(encoding='utf-8'));assert worker['status']=='ok' and worker['blender']['version']=='4.2.3'
checks=('fourDirections','rgba','camera','footprint','anchorFinite','anchorFixedAcrossDirections','materials','styleContract','fixedLighting','maskChannels','maskFrameMatchesColor','fixedColorSurfacesBlack')
assert all(worker['legacyChecks'][key] for key in checks)
manifest=json.loads((install/'ch-legacy-build.json').read_text(encoding='utf-8'));assert manifest['effectiveOptions']['WITH_CYCLES_EMBREE']=='OFF';manifest['status']='validated_on_phenom_for_ch_pipeline';manifest['validation']={'version':True,'bpy':True,'background':True,'cycles':True,'pngRGBA':True,'realRecipe':True,'camera':True,'footprintAnchor':True,'preflightProxy':True,'isaAudit':True,'embreeExperiment':True,'embreeSelected':False};manifest['validationScope']=review['scope'];manifest['embreeComparison']={'baselineMeanSeconds':comparison['meanSeconds']['baseline'],'embreeMeanSeconds':comparison['meanSeconds']['embree'],'bitExactPNGs':sum(i['bitExact'] for i in comparison['images']),'selected':'without_embree','officialReferenceAvailable':False};manifest['validationEvidenceDirectory']='legacy-validation';evidence=install/'legacy-validation';evidence.mkdir(exist_ok=True)
files={'cpu.json':root/'cpu.json','validation.json':validation/'validation.json','cycles-report.json':validation/'cycles-report.json','binary-isa-reviewed.json':validation/'binary-isa-reviewed.json','isa-review.json':HERE/'isa-review.json','worker.report.json':real/'worker.report.json','studio_metadata.json':real/'studio_metadata.json','embree-comparison.json':validation/'benchmark/comparison.json','dependency-probe.json':root/'logs/dependency-probe.json'}
for name in ('comparison_metrics.json','preflight_report.json','proxy_report.json'):files[name]=validation/'preflight'/name
for name,path in files.items():shutil.copy2(path,evidence/name)
for file in real.glob('*.png'):shutil.copy2(file,evidence/file.name)
shutil.copy2(validation/'cycles.png',evidence/'cycles.png');(install/'ch-legacy-build.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
summary={'status':manifest['status'],'cpu':manifest['cpu'],'compiler':manifest['compiler'],'architecture':manifest['architectureBaseline'],'compilerEnvironment':manifest['compilerEnvironment'],'versionLine':runtime['versionLine'],'executable':str(install/'blender.exe'),'executableSha256':hashlib.sha256((install/'blender.exe').read_bytes()).hexdigest(),'binaryFilesReviewed':len(reviewed['files']),'preflightProxy':quality,'selectedUnitTests':32,'cyclesSmoke':True,'realRecipe':True,'realChecks':worker['legacyChecks'],'embreeExperiment':manifest['embreeComparison'],'officialPNGReferenceAvailable':False,'upstreamCommit':manifest['upstreamCommit'],'patches':len(manifest['patches']),'preExistingRepositoryInventoryErrors':15,'sourceVendoredIntoCH':False};(HERE/'local-validation.json').write_text(json.dumps(summary,indent=2)+'\n',encoding='utf-8');project=HERE.parents[2];file=project/'tools/ch_blender/ch_blender_manifest.json';info=json.loads(file.read_text(encoding='utf-8'));info['executionBackends']['legacy_cpu_4_2_3'].update({'productionValidated':True,'validationScope':'Phenom II X6 1055T: headless Cycles CPU, existing color_mask_smoke recipe; no artistic promotion','localValidation':'tools/ch_blender/legacy_cpu/local-validation.json'});file.write_text(json.dumps(info,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':summary['status'],'files':summary['binaryFilesReviewed'],'executable':summary['executable'],'sha256':summary['executableSha256']},indent=2))